# Example Home Assistant configuration for Helios Cinema Card

# Add this to your configuration.yaml
helios_cinema:
  update_interval: 30  # Update every 30 minutes
  cinema_url: "https://helios.pl/wroclaw/kino-helios-magnolia"

# Add this to your ui-lovelace.yaml or dashboard configuration
# Make sure to add the resource first:
# resources:
#   - url: /local/helios-cinema-card.js
#     type: module

# Example card configuration:
# type: custom:helios-cinema-card
# entity: sensor.helios_cinema_films
# name: "Helios Cinema Wrocław"
# auto_rotate: true
# rotate_interval: 5000
# manual_timeout: 30000

# Example automation to notify about new films:
# automation:
#   - alias: "New Films Alert"
#     trigger:
#       - platform: state
#         entity_id: sensor.helios_cinema_films
#     action:
#       - service: notify.mobile_app_your_phone
#         data:
#           title: "Cinema Update"
#           message: "{{ states('sensor.helios_cinema_films') }} films available at Helios"
